### ISSUE TITLE
rat.ClassifyBehavior: Directory path error on Windows 

### ISSUE THREAD

**Issue by MariosPanayi** [pyratlib/pyrat#5] opened 2023-02-17 21:12 UTC
Hi there, I have encountered a couple of errors that pop up while trying to use the rat.ClassifyBehavior. PLease let me know if you need any additional information, hope this helps :)

####
On windows OS, for the rat.ClassifyBehavior function, the default path used by the directory parameter returns an error under the following conditions:

1) Inconsistent path requirements for WIndows OS.
If you provide a path to the "directory" parameter, it generates a different error suggesting that the folder does not exist *IF* you use \\ to separate folders in the filepath e.g. 
This generates an error:
cluster_labels, data_emb, model, data_high = rat.ClassifyBehavior(df, video ="C:\\Users\\panayimc\\Box\\DeepLabCut_NIDA\\MPNIDA004_SPC-Shohan-2021-09-20\\videos\\15_2021-09-03_11-22-22.mp4", bodyparts_list=["nose", "leftEar", "rightEar", "tailBase"], n_components = 2,  distance = 28, startIndex = 20, endIndex = 1000, directory = "C:\\Users\\panayimc\\Documents\\DeepLabCut\\images_rat" )

This does not generate an error:
cluster_labels, data_emb, model, data_high = rat.ClassifyBehavior(df, video ="C:\\Users\\panayimc\\Box\\DeepLabCut_NIDA\\MPNIDA004_SPC-Shohan-2021-09-20\\videos\\15_2021-09-03_11-22-22.mp4", bodyparts_list=["nose", "leftEar", "rightEar", "tailBase"], n_components = 2,  distance = 28, startIndex = 20, endIndex = 1000, directory = "C:/Users/panayimc/Documents/DeepLabCut/images_rat" ))

*Note that the path to the video needs to be in a different format.

2) If the folder already exists.

if the folder path provided to the directory parameter already exists (but is empty), the function also breaks with the following error:
# ----
File C:\ProgramData\Anaconda3\envs\DEEPLABCUT\lib\site-packages\pyratlib\processing.py:1545, in ClassifyBehavior(data, video, bodyparts_list, dimensions, distance, **kwargs)
   1542     break
   1544 for i in range(f,len(directory.split(sep = "/"))):
-> 1545   os.mkdir("/"+"/".join(directory.split(sep = "/")[1:i+1]))
   1547 values = (data.iloc[2:,1:].values).astype(float)
   1548 lista1 = (data.iloc[0][1:].values +" - " + data.iloc[1][1:].values).tolist()

FileExistsError: [WinError 183] Cannot create a file when that file already exists: '/images'
# ----

**Comment by tuliofalmeida** [comment] 2023-02-18 09:42
Hey Marios, thanks for message.
I'll try to reproduce your error to fix it as soon as possible!

**Comment by tuliofalmeida** [comment] 2023-02-18 12:03
Hey @MariosPanayi I did some tests and updated the code, could you test it please?
You need to update pyrat (should install version 0.7.7).
`pip install pyratlib --upgrade`

**Comment by tuliofalmeida** [comment] 2023-03-19 08:08
@MariosPanayi As I said, I think that the problem is fixed. So, I'll close this issue if you need any assistance just open it again.

**Closed as completed by tuliofalmeida** 2023-03-19 08:08 UTC
